### ISSUE TITLE
android.view.InflateException: Binary XML file line #12: Error inflating class com.looklook.xinghongfei.looklook.widget.BadgedFourThreeImageView

### ISSUE THREAD

**Issue by gwokwong** [xinghongfei/LookLook#10]
android.view.InflateException: Binary XML file line #12: Error inflating class com.looklook.xinghongfei.looklook.widget.BadgedFourThreeImageView

**Comment by xinghongfei** [comment]
Please try again,if fair，I want to know detailed information about the Error.
