### ISSUE TITLE
MeiziPresenterImpl中使用缓存的Key是Config.ZHIHU

### ISSUE THREAD

**Issue by JerryMissTom** [xinghongfei/LookLook#15]
在类MeiziPresenterImpl的getMeiziData（）这个方法中，获取数据后通过mCacheUtil.put(Config.ZHIHU, gson.toJson(meiziData))来缓存，这里使用key是Config.ZHIHU,,不该是Config.MEIZI吗？

**Comment by xinghongfei** [comment]
是的，由于大意写错了吧。欢迎pull request。
