### ISSUE TITLE
TopNewsAdapter里bindViewHolderNormal方法中insertHasRead错误使用Config.ZHIHU

### ISSUE THREAD

**Issue by JerryMissTom** [xinghongfei/LookLook#17]
DBUtils.getDB(mContext).insertHasRead(Config.ZHIHU, newsBeanItem.getTitle(), 1)应该替换为DBUtils.getDB(mContext).insertHasRead(Config.TOPNEWS, newsBeanItem.getTitle(), 1)

**Comment by xinghongfei** [comment]
是的，多谢提醒。马上就去更改。

**Comment by JerryMissTom** [comment]
我在自己fork的项目里添加了太多的注释啥的， 不然就pull requests了，只好过来添加issues。

**Comment by xinghongfei** [comment]
是呢，我的项目其中一个不足就是注解太少。

**Comment by JerryMissTom** [comment]
是的，很多工具类和控件，一些动画效果都没有注释，看上去真的蛮费力的
