### ISSUE TITLE
==打开崩溃

### ISSUE THREAD

**Issue by Kola-Chao** [xinghongfei/LookLook#19]
`android.view.InflateException: Binary XML file line #12: Error inflating class com.looklook.xinghongfei.looklook.widget.BadgedFourThreeImageView`
`at com.looklook.xinghongfei.looklook.adapter.ZhihuAdapter.onCreateViewHolder(ZhihuAdapter.java:65)`

**Comment by JerryMissTom** [comment]
这个bug在最新的pull requests貌似已经解决了，你拉取最新的代码看下
