### ISSUE TITLE
打开就崩溃

### ISSUE THREAD

**Issue by SomnusWu** [xinghongfei/LookLook#25]
android.view.InflateException: Binary XML file line #12: Error inflating class com.looklook.xinghongfei.looklook.widget.BadgedFourThreeImageView

2016年9月20日 11:43:06

**Comment by JerryMissTom** [comment]
手机连接网络没？断网状态下，打开就崩溃这个Bug已经被修复了，请下载最新的代码

**Comment by SomnusWu** [comment]
刚clone的代码  手机连接wifi

**Comment by Doracoin** [comment]
E:\my_git\LookLook\app\src\main\java\com\looklook\xinghongfei\looklook\Activity\MeiziPhotoDescribeActivity.java
Error:(266, 21) 错误: 找不到符号
符号:   方法 setRegion(int,int,int,int)
位置: 类 Builder

我这里刚刚clone了一份，编译不过，缺方法，不知道是哪个类出了问题。

**Comment by JerryMissTom** [comment]
我下载测试并没有出现这样的问题，这个app支持5.0以上版本，我用的是6.0的系统

**Comment by Doracoin** [comment]
刚刚把缺失的**setRegion** 方法注释掉了，然后在MainActivity的**super.onCreate()**这里抛了异常，目前没找到什么原因。

我使用的手机为三星 Note4 5.1的系统

**Comment by xinghongfei** [comment]
虚拟机也出现这样的情况吗？

**Comment by SomnusWu** [comment]
好吧  我用的真机      API 19

**Comment by xinghongfei** [comment]
我不知道你是什么时候clone的源码，之前有一些bug已经修复了。

**Comment by Doracoin** [comment]
昨天clone的，昨天就试了，昨天就出问题了，昨天就来这里写下问题了。

2016-9-21 14:27:49

**Comment by SomnusWu** [comment]
Android 4.4.4 API 19  报错 ， 虚拟机 5.0  就没问题   。 @JerryMissTom  说的是支持5.0 以上 。

**Comment by xinghongfei** [comment]
目前只支持5.0以上，下一步会向下兼容
