### ISSUE TITLE
NewsDetailBean.class中的属性和通过URL获取的JSON中的key不匹配

### ISSUE THREAD

**Issue by JerryMissTom** [xinghongfei/LookLook#27]
通过url获取的JSON如下：
![80325da1-8167-40f5-99fc-041123777b57](https://cloud.githubusercontent.com/assets/15966403/18696997/1074bfe0-7ff0-11e6-9e52-17e23fcd7743.png)
而最终转换到的NewsDetailBean.class中的属性如下：
![e5c469fe-e7db-4766-b3f3-a1efc991315c](https://cloud.githubusercontent.com/assets/15966403/18697025/3e43bb24-7ff0-11e6-85c9-a4ced9c4d1ba.png)
两者中的key并不是对应的，NewsDetailBean.class中的cover这个属性在JSONObject中并没有。GSON的处理是否无需二者一一对应？我没有搜到相关的资料，希望可以得到你的回答

**Comment by xinghongfei** [comment]
可以不对应，可以多或少。只要记住，JSONObject中的值必须和java实体的值一样，才可以解析。

**Comment by JerryMissTom** [comment]
你所说的是值是指JSONObject中的key和Java类中属性的@SerializeName("  ")名称吧？比如说JSONObject有一个body的key，Java实体中对应的属性@SerializeName("body")，而属性名称可以改变为private String nobody，并不强制要求为private String body。我的理解没错吧？

**Comment by xinghongfei** [comment]
是的。

**Comment by JerryMissTom** [comment]
非常感谢，我最近一周都在看这个项目，然后学习到了很多，里面也有一些自定义的view和控件我没能弄明白，要是注释更全一点儿就更好了。
