### ISSUE TITLE
CacheUtil中put(File file)问题

### ISSUE THREAD

**Issue by fuxibagua** [xinghongfei/LookLook#29]
CacheUtil类中 put(File file)方法这句中是不是应该加上 cacheCount.addAndGet(-1);呢？
 while (curCacheSize + valueSize > sizeLimit) {
                long freedSize = removeNext();
                curCacheSize = cacheSize.addAndGet(-freedSize);
            }

**Comment by xinghongfei** [comment]
是呢，你看的很细啊
