### ISSUE TITLE
编译不通过，没找到OkHttp

### ISSUE THREAD

**Issue by fantasticKB** [xinghongfei/LookLook#3]
`utils`包下的`OkHttpUtils`提示找不到OkHttp，看了一下`build.gradle`,好像没有导入`OkHttp`吧。在`build.gradle`中加入`compile 'com.squareup.okhttp:okhttp:2.7.5'`就可以正常编译了。

**Comment by xinghongfei** [comment]
昨天项目更新出来点问题，现在重新clone或fork一下
