### ISSUE TITLE
你这个侧边栏也太反人类了吧

### ISSUE THREAD

**Issue by jkgeekJack** [xinghongfei/LookLook#31]
首先不知道怎么打开侧边栏，竟然是toolbar上一个不知道代表什么的原点，其次是侧边栏竟然在左边，看到之后不知道怎么的浑身不舒服，建议改成一贯的左上角三横，然后从左边弹出

**Comment by xinghongfei** [comment]
毫无疑问，几乎所有的应用都是左边打开，但是，从用户使用习惯来讲，一般情况下，都是右手操作手机，所以侧边栏放在右边更方便。
