### ISSUE TITLE
android.support.v7.widget.Toolbar 怎么设置才能不遮挡RecyclerView的内容

### ISSUE THREAD

**Issue by 1040087877** [xinghongfei/LookLook#45]
我自己试下打了代码，为什么Toolbar 一直遮挡RecyclerView的内容，怎么改都没用，求助

**Comment by JerryMissTom** [comment]
麻烦具体描述下信息，在哪个界面，最好可以贴一下代码@1040087877

**Comment by 1040087877** [comment]
没事了 我解决了 😃

**Comment by JerryMissTom** [comment]
OK，可以具体介绍下情况不？

**Comment by 1040087877** [comment]
![621469330363006238](https://cloud.githubusercontent.com/assets/16516389/21632881/6c04d560-d285-11e6-8744-223bef7fc4a2.jpg)
就是图里 那个Toolbar 挡道了内容布局
不是代码的问题，是我自己测试的时候没注意到

**Comment by xinghongfei** [comment]
nice！
