### ISSUE TITLE
点击侧边的设置会报空指针

### ISSUE THREAD

**Issue by wildma** [xinghongfei/LookLook#52]
这下面的判断有问题
`if (currentFragment == null || !currentFragment.getClass().getName().equals(fragment.getClass().getName())) {
                System.out.println("currentFragment=22" + currentFragment);
                getSupportFragmentManager().beginTransaction().replace(R.id.fragment_container, fragment)
                        .commit();
                currentFragment = fragment;
            }`

**Comment by xinghongfei** [comment]
欢迎PR
