### ISSUE TITLE
断网情况下，App无法启动【Bug】

### ISSUE THREAD

**Issue by JerryMissTom** [xinghongfei/LookLook#8]
断网时，App无法启动，连接网络后，正常启动

**Comment by xinghongfei** [comment]
我会尽快修复的，谢谢

**Comment by JerryMissTom** [comment]
主要原因是在ZhihuFragment的onCreateView方法中，checkConnectivity(view)在ButterKnife.inject(this,view)之前调用，断网的时候checkConnectivity方法中的progress实际上并未绑定，故会报错。
我的一个疑问是：为何在ZhihuFragment中的处理与TopNewsFragment以及MeiziFragment中不同，相比较来说，后两者更简洁，是为了展示其他的设计思路吗？
PS：很感谢你的LookLook项目，里面的MVP设计体现很不错，只是我水平太低，暂时无法领悟，里面一些类及方法不能明白，假如有问题，希望不吝赐教。

**Comment by xinghongfei** [comment]
是的，这个bug很好解决，只是最近事情太多了，没想精力更新项目了。感谢你的关注和支持，共同进步。

**Comment by JerryMissTom** [comment]
简单的交换checkConnectivity和ButterKnife.inject(this,view)的位置还会出现错误，主要是没有对监听网络变化的NetworkCallback进行初始化，所以我的建议是将initialListener()这个方法中内容分拆，后半部分合并到checkConnectivity，前半部分不变，可以解决此问题。
PS：ZhihuFragment中的处理与TopNewsFragment以及MeiziFragment中不同，相比较来说，后两者更简洁，前者使用checkConnectivity的目的是监听网络，断网后重新连接至网络后自动刷新。我理解的没有错吧？
