### ISSUE TITLE
Could not find method android()

### ISSUE THREAD

**Issue by gwokwong** [xinghongfei/LookLook#9]
Error:(25, 1) A problem occurred evaluating root project 'LookLook-master'.

> Could not find method android() for arguments [build_63s1zz39rjgyp68rqkrd6bpqp$_run_closure4@76c9a98] on root project 'LookLook-master' of type org.gradle.api.Project.

**Comment by xinghongfei** [comment]
http://stackoverflow.com/questions/26243480/could-not-find-method-android-for-arguments-when-building-android-project-from
